FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime

# Use bash as default shell, rather than sh
ENV SHELL /bin/bash

COPY requirements.txt .

RUN apt update
RUN apt install -y libglib2.0-0 libsm6 libxext6 libxrender-dev git
RUN apt install -y build-essential
RUN pip install -r requirements.txt